service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10

functions:
  createProduct:
    handler: handler.createProduct
    events:
     - http:
         path: product
         method: post
         cors: true
  updateProduct:
    handler: handler.updateProduct
    events:
     - http:
         path: product/{id}
         method: put
         cors: true
  deleteProduct:
    handler: handler.deleteProduct
    events:
     - http:
         path: product/{id}
         method: delete
         cors: true
  product:
    handler: handler.getAllProducts
    events:
     - http:
         path: product
         method: get
         cors: true
  createShop:
    handler: handler.createShop
    events:
     - http:
         path: shop
         method: post
         cors: true
  updateShop:
    handler: handler.updateShop
    events:
     - http:
         path: shop/{id}
         method: put
         cors: true
  deleteShop:
    handler: handler.deleteShop
    events:
     - http:
         path: shop/{id}
         method: delete
         cors: true
  shop:
    handler: handler.getAllShops
    events:
     - http:
         path: shop
         method: get
         cors: true